language: node_js   #设置语言
node_js: stable     #设置相应的版本

cache:
    directories:
        - node_modules    #据说可以减少travis构建时间

# S: Build Lifecycle
install:
  - npm install   #安装hexo及插件

script:
  - hexo cl   #清除
  - git clone --branch master https://github.com/supersojo/supersojo.github.io.git public
  - hexo g   #生成

after_script:
  - cd ./public
  - echo "blog.linote.cn" > CNAME
  - git config user.name "Su Yanjun"   #修改成自己的github用户名
  - git config user.email "suyanjun218@163.com"   #修改成自己的GitHub邮箱
  - git status
  - git add .
  - git status
  - git commit -m "Travis CI Auto Builder ${TRAVIS_BUILD_NUMBER}"
  - git push --force  "https://${GH_TOKEN}@${GH_REF}" master:master #GH_token就是在travis中设置的token

branches:
  only:
    - master  #只监测这个分支，一有动静就开始构建（我可能发一篇文章会push好多次，每次看到它忙着构建，感觉好浪费）。
env:
    global:
        - GH_REF: github.com/supersojo/supersojo.github.io.git
